### ISSUE TITLE
Missing dependency on documentation

### ISSUE THREAD

**Issue by nejdetckenobi** [emsquid/pic#12]
You should tell users that `libsixel1` is a dependency.

**Comment by emsquid** [comment]
What is the difference between `libsixel` and `libsixel1` ?

**Comment by nejdetckenobi** [comment]
You're right. I think I have some apt src issues. Therefore I see two packages as `libsixel1` and `libsixel`. When `libsixel` is installed, the tool won't work. Not sure what's the difference between them. Thanks anyways. I'm closing it since it's not a generic thing. It's me with a messy apt.
