### ISSUE TITLE
error while loading shared libraries: libsixel.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by emsquid** [emsquid/pic#4]
I am getting that error in Konsole, can't figure it out...

**Comment by Maratripa** [comment]
I solved the issue installing libsixel.
I can reproduce the issue removing libsixel, then it goes away by installing it again. :)

**Comment by emsquid** [comment]
It's funny I didn't have that before, I will add a note in the README about this, thanks :)
